urls.py
from django.conf.urls.defaults import patterns, include, url

from settings import MEDIA_ROOT
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': MEDIA_ROOT }),
    url(r'^$', 'cdr.views.home', name='home'),
    url(r'^db/(?P<database>\w+)/$', 'cdr.views.set_db', name='set_db'),
    # url(r'^asteriskcdrdb/', include('asteriskcdrdb.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

cdr/models.py
from django.db import models
import time

DISPOSITION = (
    ('FAILED','FAILED'),
    ('ANSWERED','ANSWERED'),
    ('NO ANSWER','NO ANSWER'),
    ('BUSY','BUSY'),
)

class Cdr(models.Model):
    calldate = models.DateTimeField()
    clid = models.CharField(max_length=240)
    src = models.CharField(max_length=240)
    dst = models.CharField(max_length=240)
    dcontext = models.CharField(max_length=240)
    channel = models.CharField(max_length=240)
    dstchannel = models.CharField(max_length=240)
    lastapp = models.CharField(max_length=240)
    lastdata = models.CharField(max_length=240)
    duration = models.IntegerField()
    billsec = models.IntegerField()
    disposition = models.CharField(max_length=135)
    amaflags = models.IntegerField()
    accountcode = models.CharField(max_length=60)
    uniqueid = models.CharField(max_length=96, primary_key=True)
    userfield = models.CharField(max_length=765)
    
    class Meta:
        db_table = u'cdr'
        verbose_name = 'registro de llamada'
        verbose_name_plural = 'registros de llamadas'

    def __unicode__(self):
        return 'callid: %s "%s" (%i)' % (self.uniqueid, self.disposition, self.duration)

    @property
    def tiempo_facturado(self):
        return time.strftime('%H:%M:%S', time.gmtime(self.billsec))

class Rate(models.Model):
    date_of_rate = models.DateField()
    value = models.DecimalField(max_digits=5, decimal_places=4, default=0)

    def __unicode__(self):
        return '%s' % (self.date_of_rate)

cdr/forms.py
from django import forms
from datetime import date
from django.forms.widgets import CheckboxSelectMultiple

DISPOSITIONS = (
 ('ALL','ALL'),
 ('FAILED','FAILED'),
 ('ANSWERED','ANSWERED'),
 ('NO ANSWER','NO ANSWER'),
 ('BUSY','BUSY'),
)

class CdrSearchForm(forms.Form):
    calldate_from = forms.DateField(initial=date.today(), required=False)
    calldate_to = forms.DateField(initial=date.today(), required=False)
    disposition = forms.CharField(widget=forms.Select(choices=DISPOSITIONS), required=False)
#    widget=forms.Select(choices=TITLE_CHOICES)

cdr/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template.context import RequestContext
from cdr.models import Cdr
from datetime import date, datetime, timedelta
from cdr.forms import CdrSearchForm

#@staff_member_required
def home(request):

    if not request.GET.has_key('csrfmiddlewaretoken'):
        form = CdrSearchForm()
        registros = Cdr.objects.filter().using(request.database)
    else:
        form = CdrSearchForm(request.GET)
        if form.is_valid():
            date_from = form.cleaned_data.get('calldate_from')
            date_to = form.cleaned_data.get('calldate_to')
            if date_to:
                date_to = date_to + timedelta(days=1)

            registros = Cdr.objects.all().using(request.database)

            if date_from:
                registros = Cdr.objects.filter(calldate__gte=date_from).using(request.database)
            if date_to:
                registros = Cdr.objects.filter(calldate__lte=date_to).using(request.database)

            disposition = form.cleaned_data.get('disposition', 'ALL')
            if disposition != 'ALL':
                registros = registros.filter(disposition=disposition).using(request.database)
            
        
    return render_to_response("cdr/index.html",
                                {'registros':registros, 'form':form},
                                context_instance=RequestContext(request))

#@staff_member_required
def set_db(request, database):
    request.session['DB'] = database
    return HttpResponseRedirect(reverse('home'))

cdr/templates/cdr/inclusion_tags/databases.html
<h5>Connect to server</h5>
    <ul>
        {% for d in databases %}
            <li><a href="{% url set_db d %}">{{ d }}</a></li>
        {% endfor %}
    </ul>

cdr/templates/cdr/index.html
{% extends "base.html" %}
{% load sorting_tags pagination_tags %}

{% block extra_js %}
    <script type="text/javascript">
        $(document).ready(function(){
            $("#id_calldate_from").datepicker({ maxDate: 0, dateFormat:"dd/mm/yy" });
            $("#id_calldate_to").datepicker({ maxDate: 0, dateFormat:"dd/mm/yy" });
        });
    </script>
{% endblock %}

{% block content %}

        <div class="hero-unit">
          <form action=".">
              {% csrf_token %}
              <fieldset>
                  <legend>Filtros</legend>

                  <div class="clearfix">
                      {{ form.calldate_from.label_tag }}
                      <div class="input">
                          {{ form.calldate_from }}
                      </div>
                  </div>

                  <div class="clearfix">
                      {{ form.calldate_to.label_tag }}
                      <div class="input">
                          {{ form.calldate_to }}
                      </div>
                  </div>

                  <div class="clearfix">
                      {{ form.disposition.label_tag }}
                      <div class="input">
                          {{ form.disposition }}
                      </div>
                  </div>



              </fieldset>

              <div class="actions">
                  <input type="submit" value="Filtrar" class="btn primary large">
                  <input type="submit" value="Borrarlos" class="btn danger">
              </div>

          </form>
        </div>

        <!-- Example row of columns -->
        <div class="row" style="margin-left: 0px;">
        

            {% if registros %}
            <table class="zebra-striped">

                    <thead>
                        <tr>
                            <th>{% anchor calldate CallDate %}</th>
                            <th>duration</th>
                            <th>tiempo_facturado</th>
                            <th>{% anchor disposition Disposition %}</th>
                            <th>channel</th>
                            <th>dstchannel</th>
                            <th>dst</th>
                            <th>x</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% autosort registros %}
                        {% autopaginate registros %}
                        {% for r in registros %}
                        <tr>
                            <td>{{ r.calldate }}</td>
                            <td>{{ r.duration }}</td>
                            <td>{{ r.tiempo_facturado }}</td>
                            <td>{{ r.disposition }}</td>
                            <td>{{ r.channel }}</td>
                            <td>{{ r.dstchannel }}</td>
                            <td>{{ r.dst }}</td>
                            <td>
                                <a href="" class="btn small danger">x</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>

            </table>


            {% paginate %}
        {% else %}
                <h2>Nada que mostrar con ese criterio</h2>
        {% endif %}

        </div>







{% endblock %}

templates/base.html
{% load databases %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>CDR</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le styles -->
    <script src="{{ MEDIA_URL }}js/jquery-1.6.2.min.js"></script>
    <script src="{{ MEDIA_URL }}js/jquery-ui-1.8.16.custom.min.js"></script>
    <link href="{{ MEDIA_URL }}css/bootstrap.css" rel="stylesheet">
    <link href="{{ MEDIA_URL }}css/jquery-ui-1.8.16.custom.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 60px;
      }
    </style>


    {% block extra_js %}{% endblock %}

  </head>

  <body>

    <div class="topbar">
      <div class="topbar-inner">
        <div class="container-fluid">
          <a class="brand" href="#">CDR Master. Connected to <strong>{{ DB }}</strong></a>
          <ul class="nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
          <p class="pull-right">Logged in as <a href="#">{{ user }}</a></p>
        </div>
      </div>
    </div>

    <div class="container-fluid">

        {% block sidebar %}
        <div class="sidebar">
        <div class="well">
          <h5>Menu</h5>
          <ul>
            <li><a href="#">sync all servers</a></li>
          </ul>


            {% databases %}


            

        </div>
      </div>
        {% endblock %}


      <div class="content">

          {% block content %}
          {% endblock %}

        <footer>
          <p>&copy; CDR Master by XilverCorp</p>
        </footer>
      </div>
    </div>

  </body>
</html>

templates/export/xls.html
<table width="100%">
  <tr>
    <td>Fecha</td>
    <td>Channel</td>
    <td>Disposition</td>
    <td>DST</td>
    <td>UniqueID</td>
    <td>Tiempo</td>
  </tr>
    {% for r in registros %}
      <tr>
        <td>{{ r.calldate }}</td>
        <td>{{ r.channel }}</td>
        <td>{{ r.disposition }}</td>
        <td>{{ r.dstchannel }}</td>
        <td>{{ r.uniqueid }}</td>
        <td>{{ r.tiempo_facturado }}</td>
      </tr>
    {% endfor %}
    <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>Duracion</td>
    <td>{{ duracion_total }} mins</td>
    <td>Total</td>
    <td>${{ gran_total }}</td>
  </tr>
</table>

templates/pagination/pagination.html
{% if is_paginated %}
{% load i18n %}
<div class="pagination">
<ul>
    {% if page_obj.has_previous %}
        <li class="prev"><a href="?page={{ page_obj.previous_page_number }}{{ getvars }}{{ hashtag }}" class="prev">&lsaquo;&lsaquo; {% trans "previous" %}</a></li>
    {% else %}
        <li class="prev"><a class="disabled prev">&lsaquo;&lsaquo; {% trans "previous" %}</a></li>
    {% endif %}
    {% for page in pages %}
        {% if page %}
            {% ifequal page page_obj.number %}
                <li class="active"><a class="current page">{{ page }}</a></li>
            {% else %}
                <li><a href="?page={{ page }}{{ getvars }}{{ hashtag }}" class="page">{{ page }}</a></li>
            {% endifequal %}
        {% else %}
            <li class="disabled"><a href="#">...</a></li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}{{ getvars }}{{ hashtag }}" class="next">{% trans "next" %} &rsaquo;&rsaquo;</a></li>
    {% else %}
        <li><a class="disabled next">{% trans "next" %} &rsaquo;&rsaquo;</a></li>
    {% endif %}
</ul>
</div>
{% endif %}